# Generated by Django 4.2.6 on 2023-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicecategory",
            name="iconInput",
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="img_icon",
            field=models.ImageField(
                blank=True,
                default="service_default.png",
                null=True,
                upload_to="services_Icons",
            ),
        ),
    ]
