# Generated by Django 4.2.6 on 2023-10-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_remove_servicecategory_iconinput_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecategory",
            name="category_name",
            field=models.CharField(default="Engine services", max_length=200),
        ),
    ]
