# Generated by Django 4.2.6 on 2023-10-25 19:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_img",
                    models.ImageField(
                        blank=True,
                        default="default.png",
                        null=True,
                        upload_to="company_Logo",
                    ),
                ),
                ("logo_name", models.CharField(default="Chipped", max_length=100)),
                ("footer", models.CharField(default="Update Footer ", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContactSidebarCompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=200)),
                ("whatsapp", models.URLField(default="https://wa.me/enternumber")),
            ],
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Welcome to Our Caring Hospital", max_length=100
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="At Our Caring Hospital, we are dedicated to providing exceptional medical care with compassion and expertise. Your health and well-being are our top priorities, and we take pride in offering a wide range of medical services to meet all your healthcare needs.",
                        max_length=600,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
