# Generated by Django 4.2.6 on 2023-10-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="default", max_length=100)),
                ("image", models.ImageField(upload_to="hospital_abt_images")),
            ],
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(default="default", max_length=100)),
                (
                    "body",
                    models.TextField(
                        default="Please write the description here", max_length=600
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(
                        blank=True, default="https://www.facebook.com/", null=True
                    ),
                ),
                (
                    "whatsapp_link",
                    models.URLField(
                        blank=True, default="https://web.whatsapp.com", null=True
                    ),
                ),
                (
                    "linkedIn_link",
                    models.URLField(
                        blank=True, default="https://www.linkedin.com/", null=True
                    ),
                ),
                (
                    "twitter_link",
                    models.URLField(
                        blank=True, default="https://twitter.com", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopFooterHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(default="default", max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=models.TextField(
                blank=True,
                default="We are dedicated to providing our customers with first grade services",
                max_length=600,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="heading",
            field=models.CharField(default="Welcome to Our Website", max_length=100),
        ),
        migrations.CreateModel(
            name="TopFooterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(default="default", max_length=200)),
                ("url", models.URLField(blank=True, default="https://..", null=True)),
                (
                    "heading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="main.topfooterheading",
                    ),
                ),
            ],
        ),
    ]
