# Generated by Django 4.2.6 on 2023-10-27 06:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_aboutlist_aboutpage_socialmedialink_topfooterheading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutlist",
            name="desc",
            field=models.TextField(
                default="Please write the description here", max_length=600
            ),
        ),
        migrations.AlterField(
            model_name="aboutlist",
            name="image",
            field=models.ImageField(upload_to="about_images"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=tinymce.models.HTMLField(verbose_name="Content"),
        ),
    ]
