# Generated by Django 4.2.6 on 2023-10-27 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_aboutlist_desc_aboutlist_users_alter_aboutlist_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutlist",
            old_name="users",
            new_name="user",
        ),
    ]
